# 1. Thông tin k?t n?i SQL Server (Ch? vào Database TechHR v?a t?o)
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=TechHR;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Dotnet04@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Phép màu JPA: T? ??ng t?o b?ng d?a trên Class OOP
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true